sonar.projectKey=codesync-frontend
sonar.organization=415b0e344c6e354ffb91ceb07da13a0c0d8b4021
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**
sonar.javascript.lcov.reportPaths=coverage/codesync-frontend/lcov.info
